basePath: /
definitions:
  articles.Article:
    properties:
      author:
        $ref: '#/definitions/authors.Author'
      author_id:
        type: string
      body:
        type: string
      created_at:
        type: string
      id:
        type: string
      title:
        type: string
      updated_at:
        type: string
    type: object
  articles.ArticleInput:
    properties:
      author_id:
        type: string
      body:
        type: string
      title:
        type: string
    type: object
  articles.ArticleWithAuthor:
    properties:
      article:
        items:
          $ref: '#/definitions/articles.Article'
        type: array
      created_at:
        type: string
      email:
        type: string
      id:
        type: string
      name:
        type: string
      updated_at:
        type: string
    type: object
  authors.Author:
    properties:
      created_at:
        type: string
      email:
        type: string
      id:
        type: string
      name:
        type: string
      updated_at:
        type: string
    type: object
  authors.AuthorInput:
    properties:
      email:
        type: string
      name:
        type: string
    type: object
  infra.ErrorResponse:
    properties:
      error:
        type: string
      message:
        type: string
      success:
        type: boolean
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is the API documentation for Kumparan Project
  title: Kumparan API
  version: "1.0"
paths:
  /article/author-name:
    get:
      consumes:
      - application/json
      parameters:
      - description: Author name
        in: query
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/articles.ArticleWithAuthor'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/infra.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/infra.ErrorResponse'
      summary: Get article by author name
      tags:
      - Article
  /article/author/{id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: Author ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/articles.ArticleWithAuthor'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/infra.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/infra.ErrorResponse'
      summary: Get article with author by ID
      tags:
      - Article
  /article/create:
    post:
      consumes:
      - application/json
      parameters:
      - description: Article input
        in: body
        name: article
        required: true
        schema:
          $ref: '#/definitions/articles.ArticleInput'
      produces:
      - application/json
      responses:
        "200":
          description: UUID
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/infra.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/infra.ErrorResponse'
      summary: Create article
      tags:
      - Article
  /article/create-bulk:
    post:
      consumes:
      - application/json
      parameters:
      - description: Article input list
        in: body
        name: article
        required: true
        schema:
          items:
            $ref: '#/definitions/articles.ArticleInput'
          type: array
      produces:
      - application/json
      responses:
        "200":
          description: UUID list
          schema:
            items:
              type: string
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/infra.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/infra.ErrorResponse'
      summary: Create many article
      tags:
      - Article
  /article/search:
    get:
      consumes:
      - application/json
      parameters:
      - description: Keyword
        in: query
        name: keyword
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/articles.Article'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/infra.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/infra.ErrorResponse'
      summary: Get article by key word
      tags:
      - Article
  /article/update/{id}:
    put:
      consumes:
      - application/json
      parameters:
      - description: Article ID
        in: path
        name: id
        required: true
        type: string
      - description: Article input
        in: body
        name: article
        required: true
        schema:
          $ref: '#/definitions/articles.ArticleInput'
      produces:
      - application/json
      responses:
        "200":
          description: UUID
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/infra.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/infra.ErrorResponse'
      summary: Update article
      tags:
      - Article
  /author/create:
    post:
      consumes:
      - application/json
      parameters:
      - description: Author input
        in: body
        name: author
        required: true
        schema:
          $ref: '#/definitions/authors.AuthorInput'
      produces:
      - application/json
      responses:
        "200":
          description: UUID
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/infra.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/infra.ErrorResponse'
      summary: Create author
      tags:
      - Author
  /author/update/{id}:
    put:
      consumes:
      - application/json
      parameters:
      - description: Author ID
        in: path
        name: id
        required: true
        type: string
      - description: Author input
        in: body
        name: author
        required: true
        schema:
          $ref: '#/definitions/authors.AuthorInput'
      produces:
      - application/json
      responses:
        "200":
          description: UUID
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/infra.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/infra.ErrorResponse'
      summary: Update author
      tags:
      - Author
swagger: "2.0"
